#!/bin/bash

mkdir -p build
cd build

cmake ..
make -j4

cd ..

TEST_FILES=(
    "ks_30_0"
    "ks_50_0"
    "ks_200_0"
    "ks_400_0"
    "ks_1000_0"
    "ks_10000_0"
)

TEST_DIR="tests"

for file in "${TEST_FILES[@]}"; do
    full_path="$TEST_DIR/$file"
    if [ -f "$full_path" ]; then
        result=$(bin/backpack "$full_path")
        echo "$file ... $result"
    else
        echo -e "${RED}$file ... файл не найден в $TEST_DIR/"
    fi
done