#!/bin/bash

mkdir -p build
cd build

cmake ..
make -j4

cd ..

TEST_FILES=(
    "sc_157_0"
    "sc_330_0"
    "sc_1000_11"
    "sc_5000_1"
    "sc_10000_5"
    "sc_10000_2"
)

TEST_DIR="tests"

for file in "${TEST_FILES[@]}"; do
    full_path="$TEST_DIR/$file"
    if [ -f "$full_path" ]; then
        result=$(bin/setcover "$full_path" | awk '{print $1; exit}')
        echo "$file ... $result"
    else
        echo -e "${RED}$file ... файл не найден в $TEST_DIR/"
    fi
done